language: objective-c
osx_image: xcode7.3
script:
- xctool -project PipelineCore.xcodeproj -scheme PipelineCore build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
